#!/bin/sh
cd ~/experimental_kiwidcdr
killall tc_mrsdcdr pertecs kiwi_nc.py spectrum3 2> /dev/null
./pertecs -c displayspectrum -rate 10000 -udpi 9226 2>/dev/null &
./pertecs -c viewiq -rate 4800 -udpi 9224  2>/dev/null  &
./kiwi_nc.py -s 123.255.61.168 -p 8073 -f 7009.520 -m iq | ./KiwiSDR_dcdr -r 8 -t 6 -w 25 | ./spectrum3 -h 127.0.0.1 -r -70 -g -1000 &
./tc_mrsdcdr 
killall tc_mrsdcdr pertecs kiwi_nc.py spectrum3 2> /dev/null


